In [35]:
import sys
import os
sys.path.append(os.path.abspath(".."))

import importlib
import utils.results_plots
importlib.reload(utils.results_plots)

from utils.results_plots import load_and_prepare_data, get_aggregated_results

In [26]:
df = load_and_prepare_data("../results/")
df.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,College,MCAR,0.932237,0.818857,0.715008,0.958449,0.1,0,NaN
1,Naive,College,MCAR,0.932638,0.815059,0.713311,0.957164,0.1,0,NaN
2,Unlabeled-KNN-hard,College,MCAR,0.930233,0.810996,0.704082,0.957293,0.1,0,5.0
3,Unlabeled-KNN-proba,College,MCAR,0.933039,0.813947,0.713551,0.957492,0.1,0,5.0
4,Unlabeled-EM,College,MCAR,0.932237,0.813487,0.711111,0.956907,0.1,0,NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   method             1600 non-null   object
 1   dataset            1600 non-null   object
 2   missing_schema     1600 non-null   object
 3   accuracy           1600 non-null   float64
 4   balanced_accuracy  1600 non-null   float64
 5   f1_score           1600 non-null   float64
 6   roc_auc            1600 non-null   float64
 7   missing_rate       1600 non-null   float64
 8   fold               1600 non-null   int64
 9   n_neighbors        640 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 125.1+ KB

In [28]:
df_aggregated_folds = get_aggregated_results(df)
df_aggregated_folds

,dataset,method,missing_schema,missing_rate,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std,f1_score_mean,f1_score_std,roc_auc_mean,roc_auc_std
0,College,Naive,MAR1,0.1,0.930468,0.003820,0.809790,0.016952,0.703434,0.020815,0.957196,0.004496
1,College,Naive,MAR1,0.3,0.927902,0.004840,0.806440,0.016274,0.694538,0.021397,0.956323,0.005383
2,College,Naive,MAR1,0.5,0.926057,0.003154,0.796522,0.012887,0.682139,0.010713,0.953210,0.004365
3,College,Naive,MAR1,0.8,0.901674,0.015246,0.685352,0.100290,0.468027,0.239803,0.921496,0.010816
4,College,Naive,MAR2,0.1,0.929506,0.004406,0.810044,0.014855,0.701370,0.017864,0.956486,0.004536
...,...,...,...,...,...,...,...,...,...,...,...,...
315,Spam,Unlabeled-KNN-proba,MCAR,0.8,0.882852,0.007777,0.867342,0.012745,0.842007,0.014757,0.948488,0.006970
316,Spam,Unlabeled-KNN-proba,MNAR,0.1,0.916759,0.004863,0.907963,0.006463,0.891298,0.007078,0.968388,0.003075
317,Spam,Unlabeled-KNN-proba,MNAR,0.3,0.910237,0.005982,0.899398,0.009155,0.881484,0.009828,0.964707,0.003165
318,Spam,Unlabeled-KNN-proba,MNAR,0.5,0.900459,0.011311,0.886411,0.013688,0.866387,0.016621,0.961293,0.004472
319,Spam,Unlabeled-KNN-proba,MNAR,0.8,0.825036,0.020686,0.787128,0.028430,0.731021,0.043009,0.941858,0.005070